### ISSUE TITLE
Vaadin 7.7.1

### ISSUE THREAD

**Issue by andrelcm** [OpenESignForms/vaadin-ckeditor#56]
Widgeset does not compile with Vaadin 7.7.1.

**Comment by OpenESignForms** [comment]
Why not?  What error?  Did you check with Vaadin on whatever issue you found?

It compiles here under 7.7.1.  Does it work under 7.7.0 for you?

```
   Compiling 1 permutation
      Compiling permutation 0...
   Compile of permutations succeeded
   Compilation succeeded -- 28.391s
Linking into /Users/yozons/git/vaadin-ckeditor/VaadinCKEditor/WebContent/VAADIN/widgetsets/org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetset; Writing extras to /var/folders/2w/k4dfbvjj265_5k4g_vt_75w40000gn/T/widgetset_org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetsete6808e5b-b511-4add-b12d-1f5741747694/org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetset
   Link succeeded
   Linking succeeded -- 0.995s
```

We also updated our Open eSignForms project that uses ckeditor and it also compiled tbe widgetsets fine.

**Comment by andrelcm** [comment]
I tried the same project in OS X and it works with vaadin 7.7.1.
In Windows 10, 7.7.0 works fine, but with vaadin 7.7.1 I got this:

Search took 5ms
set 18, 2016 6:11:44 PM com.vaadin.tools.WidgetsetCompiler$1 run
GRAVE: Widgetset compilation failed
java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(Unknown Source)
	at com.vaadin.server.widgetsetutils.WidgetSetBuilder.updateWidgetSet(WidgetSetBuilder.java:74)
	at com.vaadin.tools.WidgetsetCompiler$1.run(WidgetsetCompiler.java:76)
	at java.lang.Thread.run(Unknown Source)

Widgetset compilation finished

**Comment by OpenESignForms** [comment]
Hmmm.  Did you update your Vaadin plugin on Windows 10?  Sounds like it may be a Vaadin issue.  Too bad the error message doesn't make it clear what is wrong (what's the URI value, and heck, what's an authority component?!).  We'll have to test on Windows here as we also built on OS X Eclipse.

**Comment by andrelcm** [comment]
Yes, I did. And also cleared all caches. Now I see it is an issue with vaadin. I tried compiling another project, withou ckeditor, and I am having the same problem.

**Comment by OpenESignForms** [comment]
Indeed, we also get that error on Windows.  We'll close this as it's most likely related to Vaadin, but if there's something wrong in our configs that allow it to compile on Mac OS X but not Windows 10, we can fix that.
